apiVersion: v1
kind: Service
metadata:
  name: broker-hs
  namespace: druid
  labels:
    app: broker
spec:
  ports:
  - port: 8082
    name: broker
  clusterIP: None
  selector:
    app: broker
---
apiVersion: v1
kind: Service
metadata:
  name: broker-cs
  namespace: druid
  labels:
    app: broker
spec:
  ports:
  - port: 8082
    name: broker
  selector:
    app: broker