apiVersion: v1
kind: Service
metadata:
  name: mm-hs
  namespace: druid
  labels:
    app: middlemanager
spec:
  ports:
  - port: 8084
    name: mm
  clusterIP: None
  selector:
    app: middlemanager
---
apiVersion: v1
kind: Service
metadata:
  name: mm-cs
  namespace: druid
  labels:
    app: middlemanager
spec:
  ports:
  - port: 8084
    name: mm
  selector:
    app: middlemanager