apiVersion: apps/v1
kind: Deployment
metadata:
  name: overlord
  namespace: druid
  labels:
    app: overlord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: overlord
  template:
    metadata:
      labels:
        app: overlord
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
      - name: overlord
        image: markthub/druid:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
          name: overlord
        resources:
          limits:
            cpu: "512m"
            memory: 2Gi
          requests:
            cpu: "256m"
            memory: 2Gi
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        env:
          - name: POSTGRES_URL
            value: "postgres-cs.druid.svc.cluster.local"
          - name: ZOOKEEPER_SERVER
            value: "zk-cs.druid.svc.cluster.local"
          - name: DRUID_SERVICE_PORT
            value: "8090"
          - name: DRUID_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: DRUID_SERVICE
            value: "overlord"
          - name: DRUID_JVM_ARGS
            value: "-server -Xms1G -Xmx1G -XX:MaxDirectMemorySize=2G -Daws.region=eu-west-1 -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager"
          - name: AWS_REGION
            value: eu-west-1
          - name: AWS_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: druid-secret
                key: aws_access_key
          - name: AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: druid-secret
                key: aws_secret_key
          - name: BUCKET_STORAGE
            valueFrom:
              secretKeyRef:
                name: druid-secret
                key: aws_bucket_storage
          - name: BUCKET_INDEX
            valueFrom:
              secretKeyRef:
                name: druid-secret
                key: aws_bucket_index
        livenessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: /status/health
            port: 8090
        readinessProbe:
          initialDelaySeconds: 60
          httpGet:
            path: /status/health
            port: 8090     
        volumeMounts:
        - mountPath: /var/druid/
          name: data
      volumes:
      - name: druid-secret
        secret:
          secretName: druid-secret
      - name: data
        emptyDir: {}