version: '2.1'

services:
  zookeeper:
    image: confluent/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      zk_id: "1"
  postgres:
    image: postgres:9.6-alpine
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://host.docker.internal:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
  superset:
    container_name: superset
    image: amancevice/superset:0.28.1
    ports:
      - 8088:8088
  nifi:
    container_name: nifi
    image: apache/nifi:latest
    ports:
      - 8080:8080
  broker:
    image: markthub/druid:latest
    container_name: broker
    ports:
      - "8082:8082"
    environment:
      POSTGRES_URL: postgres
      ZOOKEEPER_SERVER: zookeeper:2181
      DRUID_SERVICE: broker 
      DRUID_HOST: broker
      DRUID_SERVICE_PORT: 8082
      DRUID_JVM_ARGS: "-server -Xms1G -Xmx1G -Daws.region=eu-west-1 -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -XX:NewSize=1G -XX:MaxNewSize=1G -XX:MaxDirectMemorySize=2G -XX:+UseG1GC -XX:+PrintGCDetails -XX:+PrintGCTimeStamps"
      AWS_ACCESS_KEY: xxx
      AWS_SECRET_KEY: yyy
      AWS_REGION: eu-west-1
      BUCKET_STORAGE: di-druid-storage
      BUCKET_INDEX: di-druid-index
      LOG_LEVEL: INFO
  historical:
    image: markthub/druid:latest
    container_name: historical
    ports:
      - "8083:8083"
    environment:
      POSTGRES_URL: postgres
      ZOOKEEPER_SERVER: zookeeper:2181
      DRUID_SERVICE: historical 
      DRUID_HOST: historical
      DRUID_SERVICE_PORT: 8083
      DRUID_JVM_ARGS: "-server -Xms1G -Xmx1G -XX:MaxDirectMemorySize=2G -Daws.region=eu-west-1 -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -XX:NewSize=1G -XX:MaxNewSize=1G -XX:+UseConcMarkSweepGC -XX:+PrintGCDetails -XX:+PrintGCTimeStamps"
      AWS_ACCESS_KEY: xxx
      AWS_SECRET_KEY: yyy
      AWS_REGION: eu-west-1
      BUCKET_STORAGE: di-druid-storage
      BUCKET_INDEX: di-druid-index
      LOG_LEVEL: INFO      
  coordinator:
    image: markthub/druid:latest
    container_name: coordinator
    ports:
      - "8081:8081"
    environment:
      POSTGRES_URL: postgres
      ZOOKEEPER_SERVER: zookeeper:2181
      DRUID_SERVICE: coordinator 
      DRUID_HOST: coordinator
      DRUID_SERVICE_PORT: 8081
      DRUID_JVM_ARGS: "-server -Xms256m -Xmx256m -Daws.region=eu-west-1 -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager -Dderby.stream.error.file=var/druid/derby.log"
      AWS_ACCESS_KEY: xxx
      AWS_SECRET_KEY: yyy
      AWS_REGION: eu-west-1
      BUCKET_STORAGE: di-druid-storage
      BUCKET_INDEX: di-druid-index
      LOG_LEVEL: INFO      
  overlord:
    image: markthub/druid:latest
    container_name: overlord
    ports:
      - "8090:8090"
    environment:
      POSTGRES_URL: postgres
      ZOOKEEPER_SERVER: zookeeper:2181
      DRUID_SERVICE: overlord 
      DRUID_HOST: overlord
      DRUID_SERVICE_PORT: 8090
      DRUID_JVM_ARGS: "-server -Xms256m -Xmx256m -Daws.region=eu-west-1 -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager"
      AWS_ACCESS_KEY: xxx
      AWS_SECRET_KEY: yyy
      AWS_REGION: eu-west-1
      BUCKET_STORAGE: di-druid-storage
      BUCKET_INDEX: di-druid-index
      LOG_LEVEL: INFO      
  middlemanager:
    image: markthub/druid:latest
    container_name: middlemanager
    ports:
      - "8091:8091"
    environment:
      POSTGRES_URL: postgres
      ZOOKEEPER_SERVER: zookeeper:2181
      DRUID_SERVICE: middleManager 
      DRUID_HOST: middlemanager
      DRUID_SERVICE_PORT: 8091
      JVM_PEONS_ARGS: "-Daws.region=eu-west-1"
      DRUID_JVM_ARGS: "-server -Xms256m -Xmx256m -Daws.region=eu-west-1 -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager"
      AWS_ACCESS_KEY: xxx
      AWS_SECRET_KEY: yyy
      AWS_REGION: eu-west-1
      BUCKET_STORAGE: di-druid-storage
      BUCKET_INDEX: di-druid-index
      LOG_LEVEL: INFO      
  router:
    image: markthub/druid:latest
    container_name: router
    ports:
      - "8888:8888"
    environment:
      POSTGRES_URL: postgres
      ZOOKEEPER_SERVER: zookeeper:2181
      DRUID_SERVICE: router 
      DRUID_HOST: router
      DRUID_SERVICE_PORT: 8888
      DRUID_JVM_ARGS: "-server -Xms256m -Xmx256m -Daws.region=eu-west-1 -Duser.timezone=UTC -Dfile.encoding=UTF-8 -Djava.util.logging.manager=org.apache.logging.log4j.jul.LogManager"      
      AWS_ACCESS_KEY: xxx
      AWS_SECRET_KEY: yyy
      AWS_REGION: eu-west-1
      BUCKET_STORAGE: di-druid-storage
      BUCKET_INDEX: di-druid-index
      LOG_LEVEL: INFO      